default_language_version:
    python: python3.11

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: 'https://github.com/psf/black'
    rev: 23.12.1
    hooks:
      - id: black
        args: [--target-version=py311]
  - repo: 'https://github.com/pycqa/flake8'
    rev: 7.0.0
    hooks:
      - id: flake8
